### ISSUE TITLE
全局安装 mockstar-cli 耗时过长

### ISSUE THREAD

**Issue by micheal-zhibin** [mockstarjs/mockstar#28]
1. 用 `tnpm` 安装耗时过长，暂时发现安装时间过长的包名字叫 `os-homedir`
![image](https://user-images.githubusercontent.com/19724409/48385357-31cd1780-e729-11e8-84c6-9cbb8c48b5d7.png)

**Comment by helinjiang** [comment]
https://github.com/Unitech/pm2/issues/2700

**Comment by helinjiang** [comment]
已经移除了对 pm2 的强依赖
